Parameters:
  DBSubnetGroup:
    Type: String
    Description: "Name of the DB subnet group"
  DBInstanceClass:
    Type: String
    Description: "The instance type of the RDS instances"
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
  DBName:
    Type: String
    Description: "The name of the primary database"
  MasterUsername:
    Type: String
    Description: "The master username for the primary database"
  MasterUserPassword:
    Type: String
    NoEcho: true
    Description: "The master password for the primary database"
  Engine:
    Type: String
    Description: "The database engine to use"
    Default: "postgres"
    AllowedValues:
      - mysql
      - postgres
  EngineVersion:
    Type: String
    Description: "The version of the database engine"
    Default: "11.5"

Resources:
  CMKKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: "KMS key for RDS encryption"
      EnableKeyRotation: true
      KeyPolicy:
        Version: '2012-10-17'
        Id: "key-default-1"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:root"
            Action: "kms:*"
            Resource: "*"
          - Sid: "Allow RDS to use the key"
            Effect: "Allow"
            Principal:
              AWS: !Sub "arn:${AWS::Partition}:iam::${AWS::AccountId}:user/rds.amazonaws.com"
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"

  PrimaryDatabase:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBName: !Ref DBName
      Engine: !Ref Engine
      EngineVersion: !Ref EngineVersion
      DBInstanceClass: !Ref DBInstanceClass
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      DBSubnetGroupName: !Ref DBSubnetGroup
      MultiAZ: true
      StorageEncrypted: true
      KmsKeyId: !Ref CMKKey
      BackupRetentionPeriod: 7

  PrimarySecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: "PrimaryDBSecret"
      Description: "Secret for primary database access"
      KmsKeyId: !Ref CMKKey
      SecretString:
        !Join
          - ""
          - - '{"username":"'
            - !Ref MasterUsername
            - '","password":"'
            - !Ref MasterUserPassword
            - '"}'

  ReplicationSource:
    Type: "Custom::StackOutputs"
    Version: '1.0'
    Properties:
      ServiceToken: !ImportValue "cross-region-exports"
      StackName: !Ref AWS::StackName
      StackRegion: !Ref AWS::Region
      OutputKey: PrimaryDatabaseEndpoint

  ReplicaRegion:
    Type: "Custom::StackOutputs"
    Version: '1.0'
    Properties:
      ServiceToken: !ImportValue "cross-region-exports"
      StackName: !Ref AWS::StackName
      StackRegion: !Ref ReplicaRegion
      OutputKey: "ReadReplicaEndpoint"

  ReadReplicaDatabase:
    Type: "AWS::RDS::DBInstance"
    Properties:
      DBInstanceIdentifier: "readreplica"
      DBInstanceClass: !Ref DBInstanceClass
      SourceDBInstanceIdentifier: !Ref PrimaryDatabase
      AvailabilityZone: !Select [0, !GetAZs !Ref ReplicaRegion]
      MultiAZ: false
      StorageEncrypted: true
      KmsKeyId: !Ref CMKKey
      PubliclyAccessible: true
      VPCSecurityGroups: [ !GetAtt PrimaryDatabaseSecurityGroup.GroupId ]
      DBSubnetGroupName: !Ref DBSubnetGroup
      Tags:
        - Key: "Name"
          Value: "Read Replica"
        - Key: "Environment"
          Value: !Ref ReplicaEnvironment

  PrimaryDatabaseSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group for primary database access"
      VpcId: !Ref <YOUR_VPC_ID>
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          SourceSecurityGroupId: !Ref PrimarySecurityGroup
      Tags:
        - Key: "Name"
          Value: "Primary Database"
        - Key: "Environment"
          Value: !Ref PrimaryEnvironment

Outputs:
  PrimaryDatabaseEndpoint:
    Value: !GetAtt PrimaryDatabase.Endpoint.Address
    Description: "Primary database endpoint"
  PrimaryDatabasePort:
    Value: !GetAtt PrimaryDatabase.Endpoint.Port
    Description: "Primary database port"
  PrimarySecurityGroup:
    Value: !GetAtt PrimaryDatabase.SecurityGroups.0.GroupId
    Description: "Primary database security group ID"
  PrimarySecretArn:
    Value: !Ref PrimarySecret
    Description: "ARN of the primary database secret"
  ReadReplicaEndpoint:
    Value: !GetAtt ReadReplicaDatabase.Endpoint.Address
    Description: "Read replica endpoint"
